---
- name: Install/unistall sw applications by play scope variables
  hosts: all
  vars:
   - a: git
   - b: present
   - c: no
  tasks:
   - name: Install/unisntall
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
