---
- name: install firewall using host variables
  hosts: webserver
  tasks:
    - name: firewall
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"

...          
