---
- name: delete file if it is executable
  hosts: all
  tasks: 
     - name: check for file info 
       stat: 
         path: /tmp/file1
       register: a
     - name: display output of above module
       debug: 
          var: a
     - name: delete file1 if it is executable    
       file: 
         name: /tmp/file1   
         state: absent
       when: a.stat.executable == true
...         
